// main.c
//
// Created by fanboyan on 2025/1/16.
//

#include <stdio.h>
#include <stdlib.h>
#include "parser.h"
#include "analyzer.h"

int main(int argc, char *argv[]) {
    // Ensure the user provides a file as an argument to compile
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <source_file.opus>\n", argv[0]);
        return EXIT_FAILURE;
    }

    // Safely open given Opus source code by using function openOpusSourceCode()
    FILE *sourceCode = openOpusSourceCode(argv[1]);
    if (!sourceCode) return EXIT_FAILURE;
    
    printf("Compiling...\n");

    // Initialize the Parser and try to generate the AST for the provided sourceCode
    Parser *parser = initParser(); 
    parser->currentToken = advanceParser(parser, sourceCode);
    ASTNode *root = parseProgram(parser, sourceCode);

    // Perform semantic analyze only if there is no parsing error 
    if (parser->parseError != PARSE_ERROR_NONE) return EXIT_FAILURE;

    // Semantically analyze the Opus AST generated by the Opus parser
    SymbolTable *symbolTable = initSymbolTable();
    Analyzer *analyzer = initAnalyzer(root, symbolTable);
    printf("Analyzing...\n");

    // Display the symbol table if semantic analysis was successful
    if (analyzeProgram(analyzer, root)) displaySymbolTable(symbolTable);
    else printf("Semantic analysis failed. Errors detected.\n");

    // Close the provided sourceCode after parsing and free resources
    fclose(sourceCode);
    freeAST(root);
    
    return EXIT_SUCCESS;
}
